# Generated by Django 4.2.10 on 2025-05-14 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='supplier',
        ),
        migrations.CreateModel(
            name='IngredientLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('supplier', models.CharField(max_length=255)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='core.ingredient')),
            ],
        ),
    ]
