# Generated by Django 4.2.10 on 2025-05-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_ingredient_lot_remove_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientlot',
            name='lot',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
