# Generated by Django 4.2.10 on 2025-05-21 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_product_quantity_productlot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='productingredients',
            name='unit',
        ),
    ]
